### ISSUE TITLE
Erro ao adicionar chave pública ao chaveiro

### ISSUE THREAD

**Issue by yudi-azvd** [fga-unb/template-latex-tcc#13]
Seguindo as orientações no README, o resultado de rodar o comando

    wget -O - http://distrib.abntex2.googlecode.com/hg/debian/89C55467.asc|sudo apt-key add - 

foi:

```
--2021-11-05 17:25:19--  http://distrib.abntex2.googlecode.com/hg/debian/89C55467.asc
Resolving distrib.abntex2.googlecode.com (distrib.abntex2.googlecode.com)... 2800:3f0:4003:c08::52, 142.251.0.82
Connecting to distrib.abntex2.googlecode.com (distrib.abntex2.googlecode.com)|2800:3f0:4003:c08::52|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-11-05 17:25:19 ERROR 404: Not Found.

gpg: no valid OpenPGP data found.
```

Tentei com a flag `no-check-certificate` pro `wget`, mas também não funcionou.

Como proceder?

**Comment by edsomjr** [comment]
Boa tarde, Yudi.

Estas instruções de instalação estão desatualizadas. Em breve vou atualizar todo o modelo, estas instruções inclusive.

Faz algum tempo que o pacote ABNTex está presente na maioria dos pacotes LaTeX das distribuições Linux (em geral, no pacote latex-extra). Existe também, no Ubuntu, o pacote abntex, mas confesso que este eu ainda não instalei/testei.

Use o comando

`$ sudo apt-get install texlive-latex-extra`

caso esteja usando uma distro que tenha o apt como gerenciador de pacotes.

**Comment by yudi-azvd** [comment]
Obrigado por responder.

No ubuntu 18, apenas instalar o `texlive-latex-extra` não foi o suficiente (posso ter me enganado em algum passo).

Consegui seguir o restante das instruções seguindo as orientações dessa wiki do [abntex](https://github.com/abntex/abntex2/wiki/InstalacaoLinux#instala%C3%A7%C3%A3o-autom%C3%A1tica-do-texlive-e-do-abntex2-em-distribui%C3%A7%C3%B5es-debian-ubuntu-e-derivadas-recomendadohttps://github.com/abntex/abntex2/wiki/InstalacaoLinux#instala%C3%A7%C3%A3o-autom%C3%A1tica-do-texlive-e-do-abntex2-em-distribui%C3%A7%C3%B5es-debian-ubuntu-e-derivadas-recomendado). O comando para a instalação dos pacotes necessários foi:

    sudo apt-get install texlive-publishers texlive-lang-portuguese texlive-latex-extra texlive-fonts-recommended
